//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 02:14:15 PM IST 
//


package com.jeet.api;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.cfg.AnnotationConfiguration;
import org.hibernate.tool.hbm2ddl.SchemaExport;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="deviceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="token1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="token2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings({ "deprecation", "unused" })
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"id",
    "deviceId",
    "token1",
    "token2"
})
@XmlRootElement(name = "tokens")
@Entity
public class Tokens {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    protected int id;
    @XmlElement(required = true)
    protected String deviceId;
    @XmlElement(required = true)
    protected String token1;
    @XmlElement(required = true)
    protected String token2;

//TODO: get back the device list
    
    /**
     * Gets the value of the Id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the Id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }
    
    /**
     * Gets the value of the deviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevice() {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevice(String value) {
        this.deviceId = value;
    }

    /**
     * Gets the value of the token1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken1() {
        return token1;
    }

    /**
     * Sets the value of the token1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken1(String value) {
        this.token1 = value;
    }

    /**
     * Gets the value of the token2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken2() {
        return token2;
    }

    /**
     * Sets the value of the token2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken2(String value) {
        this.token2 = value;
    }
    
    
    /*
    public static void main( String[] args )
    {
        AnnotationConfiguration config = new AnnotationConfiguration();
        config.addAnnotatedClass(Movie.class );
        config.configure();
        new SchemaExport(config).create(true, true);
    }*/
}


